// examples/nextjs-app/app/login/page.tsx
'use client';

import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';

const SITE_ID = process.env.NEXT_PUBLIC_AARDWIN_SITE_ID ?? '';

// 示例页视觉：中性面 + 发丝边框 + 品牌深绿 —— 与 <aardwin-auth> 组件 token 同源。
const CARD: React.CSSProperties = {
  maxWidth: 400,
  margin: '10vh auto 0',
  padding: '36px 32px',
  fontFamily:
    "system-ui,-apple-system,'Segoe UI',Roboto,'PingFang SC','Microsoft YaHei',sans-serif",
  border: '1px solid #e3e6ea',
  // Next.js 品牌色顶栏（与 Vue 示例的绿色区分，demo 双产品演示时一眼可辨）。
  borderTop: '3px solid #000',
  borderRadius: 14,
  background: '#fff',
  boxShadow: '0 1px 2px rgba(16,24,40,.04), 0 12px 32px rgba(16,24,40,.06)',
};

// 技术标识 pill：黑底白字，标识本示例的技术栈。
const PILL: React.CSSProperties = {
  display: 'inline-block',
  margin: '0 0 20px',
  padding: '3px 10px',
  borderRadius: 999,
  background: '#000',
  color: '#fff',
  fontSize: 11,
  fontWeight: 600,
  letterSpacing: '0.02em',
};

const TITLE: React.CSSProperties = {
  margin: '0 0 6px',
  fontSize: 20,
  fontWeight: 700,
  letterSpacing: '-0.01em',
  color: '#16181d',
};

const SUB: React.CSSProperties = {
  margin: '0 0 24px',
  fontSize: 13,
  color: '#5b616e',
};

const ERROR: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  gap: 12,
  marginBottom: 16,
  padding: '10px 12px',
  border: '1px solid #f1d5d3',
  borderRadius: 10,
  background: '#fdf3f2',
  color: '#b42318',
  fontSize: 13,
};

const RETRY: React.CSSProperties = {
  padding: '5px 12px',
  border: '1px solid #e3e6ea',
  borderRadius: 8,
  background: '#fff',
  color: '#16181d',
  fontSize: 12,
  fontWeight: 600,
  cursor: 'pointer',
};

function LoginPageInner() {
  const searchParams = useSearchParams();
  const lang = (searchParams.get('lang') ?? 'en') as 'zh' | 'en';
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    void import('@aardwin/auth-browser');
    // 演示监听组件事件（错误态由组件自身在 shadow DOM 内渲染；此处同步宿主提示）。
    const onError = (e: Event) => {
      const detail = (e as CustomEvent)?.detail;
      setError(detail?.message ?? 'Authentication error');
    };
    window.addEventListener('aardwin:error', onError);
    return () => {
      window.removeEventListener('aardwin:error', onError);
    };
  }, []);

  return (
    <main style={CARD}>
      <h1 style={TITLE}>Sign in</h1>
      <p style={SUB}>Continue with one of the providers below</p>
      <span style={PILL}>Next.js 15 · React 19</span>
      {error && (
        <div style={ERROR} role="alert">
          <span>{error}</span>
          <button style={RETRY} onClick={() => window.location.reload()}>
            Retry
          </button>
        </div>
      )}
      {/* 组件自带骨架屏 loading / 错误态，无需宿主额外指示 */}
      <aardwin-auth
        site-id={SITE_ID}
        i18n={lang}
        style={{ display: error ? 'none' : 'block' }}
      />
    </main>
  );
}

export default function LoginPage() {
  return (
    <Suspense
      fallback={
        <main style={{ maxWidth: 400, margin: '10vh auto 0', padding: 36, fontFamily: 'system-ui' }}>
          <div
            style={{
              height: 44,
              borderRadius: 12,
              background:
                'linear-gradient(90deg,#f1f2f4 25%,#f8f9fa 37%,#f1f2f4 63%)',
              backgroundSize: '400% 100%',
            }}
          />
        </main>
      }
    >
      <LoginPageInner />
    </Suspense>
  );
}

// examples/vue-app/src/views/Login.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();

// Public site id — the same value is rendered in the browser tag and used by the
// server-side callback. It is safe to expose.
const siteId = import.meta.env.VITE_AARDWIN_SITE_ID ?? '';

// Optional callback path. Empty string / undefined means the SDK will not send
// return_url; the bff will fall back to the callbackUrl registered in the console.
const callbackPath = import.meta.env.VITE_AARDWIN_CALLBACK_PATH ?? '';

// ?lang= query overrides the default 'en' locale passed to the custom element.
const lang = computed(() => {
  const raw = route.query.lang;
  const value = Array.isArray(raw) ? raw[0] : raw;
  return value === 'zh' ? 'zh' : 'en';
});

const error = ref<string | null>(null);

onMounted(() => {
  // Surface component-level errors in the host UI. The component already renders
  // an inline error banner inside the shadow DOM; this host banner duplicates the
  // message so it is visible outside the component and offers a Retry reload.
  const onError = (e: Event) => {
    const detail = (e as CustomEvent).detail;
    error.value = detail?.message ?? 'Authentication error';
  };
  window.addEventListener('aardwin:error', onError);

  onUnmounted(() => {
    window.removeEventListener('aardwin:error', onError);
  });
});

function retry() {
  window.location.reload();
}
</script>

<template>
  <div class="login-card">
    <h1 class="title">Sign in</h1>
    <p class="subtitle">Continue with one of the providers below</p>
    <span class="tech-pill">Vue 3 · Vite · vue-router</span>

    <div v-if="error" class="error-banner" role="alert">
      <span>{{ error }}</span>
      <button class="retry-btn" @click="retry">Retry</button>
    </div>

    <!--
      The custom element is imported once in src/main.ts. The component fetches the
      provider list for this siteId from the aardwin api and renders the buttons.
      :callback-path is bound only when the env variable is non-empty; an empty value
      would cause the SDK to omit return_url and rely on the registered callbackUrl.
      :i18n is bound to the reactive lang computed so the query string is honored.
    -->
    <aardwin-auth
      :site-id="siteId"
      :i18n="lang"
      :callback-path="callbackPath || undefined"
    />
  </div>
</template>

<style scoped>
.login-card {
  max-width: 400px;
  margin: 10vh auto 0;
  padding: 36px 32px;
  border: 1px solid #e3e6ea;
  /* Vue 品牌色顶栏（#42b883，与 Next.js 示例的黑色区分，demo 双产品演示时一眼可辨）。 */
  border-top: 3px solid #42b883;
  border-radius: 14px;
  background: #fff;
  box-shadow: 0 1px 2px rgba(16, 24, 40, 0.04), 0 12px 32px rgba(16, 24, 40, 0.06);
}

/* 技术标识 pill：Vue 品牌绿底白字。 */
.tech-pill {
  display: inline-block;
  margin: 0 0 20px;
  padding: 3px 10px;
  border-radius: 999px;
  background: #42b883;
  color: #fff;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.02em;
}

.title {
  margin: 0 0 6px;
  font-size: 20px;
  font-weight: 700;
  letter-spacing: -0.01em;
  color: #16181d;
}

.subtitle {
  margin: 0 0 24px;
  font-size: 13px;
  color: #5b616e;
}

.error-banner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 16px;
  padding: 10px 12px;
  border: 1px solid #f1d5d3;
  border-radius: 10px;
  background: #fdf3f2;
  color: #b42318;
  font-size: 13px;
}

.retry-btn {
  padding: 5px 12px;
  border: 1px solid #e3e6ea;
  border-radius: 8px;
  background: #fff;
  color: #16181d;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
}
</style>
